name: Lint Code Base

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4 for better performance
        with:
          fetch-depth: 0  # Required for `super-linter`

      - name: Run Super-Linter
        uses: super-linter/super-linter@latest  # Use latest stable version
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main  # Change to `main` since you use `main` in PRs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
